name: Test deploy on SarahConnor

on:
  push:
    branches: [ "master" ]

jobs:
  chekout:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
  wakeup:
    runs-on: self-hosted
    steps:
      - name: docker up
        run: ls -la
