name: Test deploy on SarahConnor

on:
  push:
    branches: [ "master" ]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
  wakeup:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: docker up
        run: docker run -p 3000:3000 my-node-app
