name: Test deploy on SarahConnor

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: eto test
        uses: actions/checkout@v3
      - name: eto outln
        run: ls -la
